=== rujfyls/learning-xml/src/main/resources/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="persons" type="personsType"/>

    <xs:complexType name="adressType">
        <xs:sequence>
            <xs:element type="xs:string" name="city"/>
            <xs:element type="xs:string" name="country"/>
            <xs:element type="xs:string" name="street"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:decimal" name="telephone"/>
            <xs:element type="adressType" name="adress"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="login" use="optional"/>
        <xs:attribute type="xs:string" name="faculty" use="optional"/>
    </xs:complexType>

    <xs:complexType name="personsType">
        <xs:sequence>
            <xs:element type="personType" name="person" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== rujfyls/learning-xml/src/main/resources/person.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="person.xsd">

    <person login="rujfyls" faculty="CS">
        <name>Alexander</name>
        <telephone>27</telephone>
        <adress>
            <city>balakhna</city>
            <country>RUSSIA</country>
            <street>Olimpiyskaya</street>
        </adress>
    </person>

    <person login="kefirchik" faculty="BIO">
        <name>Ekaterina</name>
        <telephone>26</telephone>
        <adress>
            <city>balakhna</city>
            <country>RUSSIA</country>
            <street>Vladimirkaya</street>
        </adress>
    </person>
</persons>
